---
title: "MP4"
author: "Ruth Tekleab Mekbib and Dee Graham"
date: "April 30, 2019"
output:
  html_document:
    code_folding: hide
---

```{r message = FALSE, warning = FALSE}
library(tidyverse)
library(RMySQL)
db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "imdb")
knitr::opts_chunk$set(connection = db, max.print = 20)
```


```{r}
man <- db %>%
  dbGetQuery("SELECT *
              FROM title
              WHERE production_year >= 2005 AND production_year <=2015
              AND kind_id = 1
              AND title like '% man %' ;")%>%

mutate (gender= "M")
```


```{r}
woman <- db %>%
  dbGetQuery("SELECT *
              FROM title
               WHERE production_year >= 2005 AND production_year <=2015
              AND kind_id = 1
              AND title like '% woman %' ;") %>%

mutate (gender= "W")
```

```{r}
#joining the two tables
man_woman<- rbind(man, woman)

```

```{r}
#man_woman %>%
#group_by(production_year) %>%
  #summarise(N= n(), count(title))
```

```{r}
Man_v_woman <- ggplot(man_woman, aes(x = production_year, fill = gender))+
  geom_bar(position = "dodge")
  

Man_v_woman
```


Ask about making another graph for leading roles/director by gender etc.






**Footnotes:**

GitHub repository:

https://github.com/DeeG2020/MiniProject4.git 